### ISSUE TITLE
Fix metric firing docs and defaults

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/go-http-api#11]
`agg` needs to be CAPS ... so the docs, default and logger are all wrong: https://github.com/praekelt/go-http-api/blob/develop/go_http/send.py#L84

Replicate with:
```
from go_http import HttpApiSender

VUMI_GO_ACCOUNT_KEY = "x"
VUMI_GO_CONVERSATION_KEY = "x"
VUMI_GO_CONVERSATION_TOKEN = "x"

sender = HttpApiSender(
    account_key=VUMI_GO_ACCOUNT_KEY,
    conversation_key=VUMI_GO_CONVERSATION_KEY,
    conversation_token=VUMI_GO_CONVERSATION_TOKEN
)

metric = "test.rising"
value = 10
newmetric = sender.fire_metric(metric, value)
```
working:
```
metric = "test.rising"
value = 10
agg = "LAST"
newmetric = sender.fire_metric(metric, value, agg)

**Comment by imsickofmaps** [comment]
@hodgestar would love this included in the next sprint. It's making a live repo tests fail now because the asserts are wrong.

**Comment by hodgestar** [comment]
I've had a look and the go-http-api is correct. The Vumi Go HTTP API itself is at fault. I've opened https://github.com/praekelt/vumi-go/issues/1198.
